name: Obfuscate JavaScript code

on: push

jobs:
  obfuscate_code:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Checkout code from core-dev
        uses: actions/checkout@v2
        with:
          path: core-dev

      - name: Remove remote
        working-directory: core-dev
        run: find . -type f | grep -i "\.git" | xargs rm

      # In this step you generally need to run some related command lines
      # of the JavaScript Obfuscator Tool to obfuscate the JavaScript code.
      # see 'https://github.com/javascript-obfuscator/javascript-obfuscator#cli-usage'

      - name: Checkout code from Repos-02
        uses: actions/checkout@v2
        with:
          repository: 'shivansh-personal/core-prod'
          token: ${{ secrets.MY_GITHUB_PAT }}
          path: core-prod
          
      - name: Check LS
        working-directory: core-prod
        run: ls
        
      - name: Copy files
        run: cp -r core-dev/core.js core-prod/

      - name: Check LS
        working-directory: core-prod
        run: |
          ls
          npm i -g javascript-obfuscator
          javascript-obfuscator core.js --output core.js
          cat core.js
          git config --global user.name "shivansh"
          git config --global user.email "shivansh@cognitivegarage.ai"
          ls
          git status
          git add -A
          git status
          git commit -m "Obfuscate JavaScript code"
          git push
          ls
          
