name: Obfuscate JavaScript code

on: push

jobs:
  obfuscate_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from code branch
        uses: actions/checkout@v2
        with:
          path: core-dev

      - name: Remove remote
        working-directory: core-dev
        run: find . -type f | grep -i "\.git" | xargs rm

      # In this step you generally need to run some related command lines
      # of the JavaScript Obfuscator Tool to obfuscate the JavaScript code.
      # see 'https://github.com/javascript-obfuscator/javascript-obfuscator#cli-usage'


      - name: Checkout code from master branch
        uses: actions/checkout@v2
        with:
          path: core-prod

      # Copy files from b_code into b_master, the new obfuscated JavaScript files
      # will be copied to overwrite the old obfuscated JavaScript files in b_master.
      - name: Copy files
        run: cp -r core-dev/core.js core-prod

      - name: Push to remote master branch
        working-directory: core-prod
        run: |
          git config --global user.name "shivansh"
          git config --global user.email "shivansh@cognitivegarage.ai"
          git add -A
          git commit -m "Obfuscate JavaScript code"
          git push
